### ISSUE TITLE
install failure

### ISSUE THREAD

**Issue by esumerfd** [dotariel/denim#1]
Something to do with GOPATH? Should I have change something?

denim: sudo make install
Password:
go get -v .
github.com/dotariel/denim (download)
created GOPATH=~/go; see 'go help gopath'
github.com/manifoldco/go-base32 (download)
github.com/emersion/go-vcard (download)
github.com/pkg/browser (download)
github.com/spf13/cobra (download)
github.com/spf13/pflag (download)
go get: no install location for directory $X/denim outside GOPATH
	For more details see: 'go help gopath'
make: *** [dep] Error 1

Don't like having to sudo to install.

**Comment by dotariel** [comment]
Did you clone the repository using `go get github.com/dotariel/denim`?

**Comment by esumerfd** [comment]
> go get github.com/dotariel/denim
> error: pathspec 'get' did not match any file(s) known to git.
